# worker process 관련 기본 이벤트 설정
events {}

http {

    server {

        # nginx가 80번 포트에서 HTTP 요청 수신
        listen 80;

        # =========================
        # Backend API 요청 처리
        # =========================
        # /api 로 시작하는 요청은 Spring Boot backend 컨테이너로 전달
        # localhost가 아니라 docker-compose 서비스 이름(backend)으로 통신
        location /api/ {

            # backend 컨테이너의 8080 포트로 요청 전달
            proxy_pass http://backend:8080/;

            # 원래 요청 Host 정보 전달
            proxy_set_header Host $host;

            # 실제 클라이언트 IP 전달
            proxy_set_header X-Real-IP $remote_addr;

            # 프록시 서버 거친 IP 정보 전달
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # HTTPS 여부 전달
            proxy_set_header X-Forwarded-Proto $scheme;
        }


        # =========================
        # Frontend 요청 처리
        # =========================
        # /api 제외한 모든 요청은 frontend 컨테이너로 전달
        location / {

            # frontend 컨테이너의 3000 포트로 요청 전달
            proxy_pass http://frontend:3000;

            # 원래 요청 Host 정보 전달
            proxy_set_header Host $host;

            # 실제 클라이언트 IP 전달
            proxy_set_header X-Real-IP $remote_addr;

            # 프록시 서버 거친 IP 정보 전달
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # HTTPS 여부 전달
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}